### ISSUE TITLE
Version number issue

### ISSUE THREAD

**Issue by Maks3w** [blackfireio/blackfire-cookbook#1]
Looks this repo has been promoted as official cookbook for blackfire.

But the version number has been reset. This is totally wrong.

See the versions published in supermarket (https://supermarket.chef.io/cookbooks/blackfire)

People which already is using this cookbook never will get the updates until a version greater than 1.0.5 is published.

No matter if you delete "old" versions from supermarket webpage, our local caches will still pointing to 1.0.5

So you should restore the version or publish a new mayor version (2.0.0)

**Comment by tucksaun** [comment]
Hello @Maks3w,

We were actually fixing that when you opened this issue.
We promoted a new major version (2.0.0) to avoid any trouble.

Thanks for the report :)
